# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  install-packages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm ci and npm run build
        run: npm ci

      - name: Install Ionic dependencies
        run: |
          npm install -g @ionic/cli
          npm install -g cordova-res

  build:
    needs: install-packages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: npm run build:ci
        run: npm run build:ci

  lint:
    needs: install-packages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: npm lint
        run: npm run lint

  test:
    needs: install-packages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: npm test:ci
        run: npm run test:ci

  e2e:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: e2e tests
        run: npm run e2e:ci
